In [1]:
import numpy as np

In [2]:
def jacobi(A, b, x):
    n = len(A)
    x_new = np.zeros_like(x)

    for i in range(n):

        somme = np.dot(A[i,:i], x[:i]) + np.dot(A[i, i+1:], x[i+1:])
        x_new[i] = (b[i]- somme) / A[i, i]
    return x_new

In [3]:
def gauss_seidel_relaxation(A, b, x, omega=1.0):
   
    n = len(A)
    x_new = x.copy()  
    
    for i in range(n):
        somme1 = np.dot(A[i, :i], x_new[:i]) 
        somme2 = np.dot(A[i, i+1:], x[i+1:])  
        x_new[i] = (1 - omega) * x[i] + omega * (b[i] - somme1 - somme2) / A[i, i]
    
    return x_new


In [4]:
def iterative_solver(A, b, x0, epsilon=1e-6, it_max=100, method='jacobi', omega=1.0):
  
    x = x0.copy()
    nb = 0
    r = np.linalg.norm(b - np.dot(A, x))
    
    while r > epsilon and nb < it_max:
        if method == 'jacobi':
            x_new = jacobi(A, b, x)
        elif method == 'gs_sor':
            x_new = gauss_seidel_relaxation(A, b, x, omega)
        else:
            raise ValueError("Méthode inconnue")
        
        x = x_new
        r = np.linalg.norm(b - np.dot(A, x))
        nb += 1
    
    if r < epsilon:
        print(f"Solution trouvée après {nb} itérations.")
        print(x)
    else:
        print(f"Pas de convergence après {it_max} itérations.")
    
    return x


In [5]:
A = np.array([[4, -1, 0, 0, 4],
              [-1, 4, -1, 0, 0],
              [0, -1, 4, -1, 0],
              [0, -2, 3, 8, 2],
              [0, 0, -1, 3, 6],])

b = np.array([15, 10, 10, 10, 10])
x0 = np.zeros(len(b))

x_jacobi = iterative_solver(A, b, x0, method='jacobi')

x_gs = iterative_solver(A, b, x0, method='gs_sor', omega=1.25)
x_gsS = iterative_solver(A, b, x0, method='gs_sor', omega=1.0)



Solution trouvée après 26 itérations.
[2.69736833 4.07894741 3.61842105 0.3947368  2.07236838]
Solution trouvée après 17 itérations.
[2.69736824 4.07894732 3.61842103 0.3947368  2.07236843]
Solution trouvée après 10 itérations.
[2.69736846 4.0789474  3.61842106 0.39473684 2.07236842]


In [6]:
A = np.array([[2, 3],
              [3, 2]])

b = np.array([5, 5])
x0 = np.zeros(len(b))
x_jacobi = iterative_solver(A, b, x0, method='jacobi')
x_gs = iterative_solver(A, b, x0, method='gs_sor', omega=1.0)
x_gs = iterative_solver(A, b, x0, method='gs_sor', omega=1.25)

Pas de convergence après 100 itérations.
Pas de convergence après 100 itérations.
Pas de convergence après 100 itérations.
